source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'XNBaseController_Example' do
  pod 'XNBaseController', :path => '../'

  target 'XNBaseController_Tests' do
    inherit! :search_paths

    
  end
end
